const imagesAddresses = {
  icons: {
    stare: "/icons/stare.svg",
    bookIcon: "/icons/bookIcon.svg",
    bookIconWhite: "/icons/bookIconWhite.svg",
    backward: "/icons/backward.svg",
    forward: "/icons/forward.svg",
    indicatorBrand: "/icons/indicatorBrand.svg",
    mute: "/icons/mute.svg",
    pause: "/icons/pause.svg",
    play: "/icons/play1.svg",
    volume: "/icons/volume.svg",
    playWhite: "/icons/play2.svg",
    greenBook: "/icons/greenBook.svg",
    list: "/icons/list.svg",
    calender: "/icons/calender.svg",
    warning: "/icons/warning.svg",
    success: "/icons/success.svg",
    verify: "/icons/verify.svg",
    closeMenue: "/icons/closeMenue.svg",
    closeMenueDark: "/icons/closeMenueDark.svg",
    menue: "/icons/menu.svg",
    support: "/icons/supportIcon.svg",
    blackEdit: "/icons/blackEdit.svg",
    save: "/icons/save.svg",
    serach: "/icons/search.svg",
    eyeWhite: "/icons/eyeWhite.svg",
    blind: "/icons/blind.svg",
    arrowRightYellow: "/icons/arrowRightYellow.svg",
    arrowRightYellow2: "/icons/arrowRightYellow2.svg",
    darkLightMode: "/icons/dark-lightMode.svg",
    darkLightMode2: "/icons/dark-lightModeWhite.svg",
    FrameWhite: "/icons/FrameWhite.svg",

    home: "/icons/home.svg",
    homeActive: "/icons/homeActive.svg",
    allUser: "/icons/allUser.svg",
    allUserActive: "/icons/allUserActive.svg",
    allBooks: "/icons/allBooks.svg",
    allBooksActive: "/icons/allBooksActive.svg",
    borrowReq: "/icons/borrowReq.svg",
    borrowReqActive: "/icons/borrowReqActive.svg",
    accountReq: "/icons/accountReq.svg",
    accountReqActive: "/icons/accountReqActive.svg",
    logout: "/icons/logout.svg",
    delete: "/icons/delete.svg",
    edit: "/icons/edit.svg",
    receipt: "/icons/receipt.svg",
    close: "/icons/close.svg",
    modalClose: "/icons/modalClose.svg",
    loading: "/icons/loading.svg",
    plus: "/icons/plus.svg",
    plus2: "/icons/plus2.svg",
    upload: "/icons/upload.svg",
    check: "/icons/check.svg",
    arrowLeft: "/icons/arrow-left.svg",
    eye: "/icons/Eye.svg",
    calendar: "/icons/calendar.svg",
    whiteEdit: "/icons/whiteEdit.svg",
    hamburgerMenu: "/icons/hamburgerMenu.svg",
    arrowRight: "/icons/arrowRight.svg",
    deny: "/icons/deny.svg",
    approve: "/icons/approve.svg",
    handle: "/icons/handle.svg",
  },
  images: {
    logo: "/images/Frame.png",
    loginPic: "/images/loginPic.png",
    loginBg: "/images/loginBg.png",
    book1: "/images/book1.png",
    book2: "/images/book2.png",
    book3: "/images/book3.png",
    book4: "/images/book4.png",
    book5: "/images/book5.png",
    book6: "/images/book6.png",
    book7: "/images/book7.png",
    book8: "/images/book8.png",
    book1blur: "/images/book1blur.png",
    emptyResult: "/images/emptyResult.png",
    profile: "/images/profile.png",
    notFoundBg: "/images/notFoundBg.png",


    adminLogo: "/images/adminLogo.png",
    avatar1: "/images/avatar1.png",
    avatar2: "/images/avatar2.png",
    avatar3: "/images/avatar3.png",
  },
} as const;

export default imagesAddresses;
