const SiteUrls = {
  home: "/",
  signIn: "/auth/sign-in",
  signUp: "/auth/sign-up",
  logout: "/auth/logout",
  forgetPass: "/auth/forget-pass",
  resetPass: "/auth/reset-pass",
  bookDetail: "/bookDetail",
  dashbord: "/dashbord",
  profile: "/profile",
  search: "/search",
  about: "/about",
  contact: "/contact",
  rootNotFound: "/notFoundRoot",

  admin: "/admin",
  adminAllUser: "/admin/allUser",
  adminAllBooks: "/admin/allBooks",
  adminAddBook: "/admin/allBooks/add",
  adminEditBook: "/admin/allBooks/edit",
  adminDetailBook: "/admin/allBooks/detail",
  adminBorrowReq: "/admin/borrowReq",
  adminAccountReq: "/admin/accountReq",
  allAdmins: "/admin/allAdmin",
  adminNotFound: "/admin/notFoundAdmin",
  adminLogin: "/admin/auth/adminLogin",
  adminRgister: "/admin/auth/adminRgister",
  adminForgetPass: "/admin/auth/adminForgetPass",
  adminResetPass: "/admin/auth/adminResetPass",
};

export default SiteUrls;